// ===============================================================
// Flutter HRMS Pro
// Designation Form
//
// Company Owner Login Based
//
// UI:
// Theme Aware
// Responsive
// Mobile / Tablet / Desktop
// Professional HRMS Design
//
// Business Logic:
// Unchanged
// companyId is NOT handled here
// code is generated by database trigger
//
// ===============================================================

import 'package:flutter/material.dart';

import '../../../../core/widgets/app_button.dart';
import '../../../../core/widgets/app_checkbox.dart';
import '../../../../core/widgets/app_text_field.dart';

class DesignationForm extends StatefulWidget {
  const DesignationForm({
    super.key,

    // -------------------------------------------------------------
    // INITIAL VALUES
    // -------------------------------------------------------------

    this.initialName = '',
    this.initialDescription = '',
    this.initialGrade = 1,
    this.initialDisplayOrder = 0,
    this.initialBaseSalary = 0,
    this.initialIsActive = true,

    // -------------------------------------------------------------
    // STATE
    // -------------------------------------------------------------

    this.isLoading = false,

    // -------------------------------------------------------------
    // CALLBACK
    // -------------------------------------------------------------

    required this.onSubmit,
  });

  final String initialName;
  final String initialDescription;

  final int initialGrade;
  final int initialDisplayOrder;

  final double initialBaseSalary;

  final bool initialIsActive;

  final bool isLoading;

  // =============================================================
  // SUBMIT
  // =============================================================

  final Future<void> Function(
      String name,
      String description,
      int grade,
      int displayOrder,
      double baseSalary,
      bool isActive,
      ) onSubmit;

  @override
  State<DesignationForm> createState() =>
      _DesignationFormState();
}

// ===============================================================
// STATE
// ===============================================================

class _DesignationFormState
    extends State<DesignationForm> {
  final _formKey = GlobalKey<FormState>();

  // -------------------------------------------------------------
  // CONTROLLERS
  // -------------------------------------------------------------

  late final TextEditingController _nameController;
  late final TextEditingController _descriptionController;
  late final TextEditingController _gradeController;
  late final TextEditingController _displayOrderController;
  late final TextEditingController _baseSalaryController;

  // -------------------------------------------------------------
  // STATUS
  // -------------------------------------------------------------

  late bool _isActive;

  // =============================================================
  // INIT
  // =============================================================

  @override
  void initState() {
    super.initState();

    _nameController = TextEditingController(
      text: widget.initialName,
    );

    _descriptionController = TextEditingController(
      text: widget.initialDescription,
    );

    _gradeController = TextEditingController(
      text: widget.initialGrade.toString(),
    );

    _displayOrderController = TextEditingController(
      text: widget.initialDisplayOrder.toString(),
    );

    _baseSalaryController = TextEditingController(
      text: widget.initialBaseSalary.toString(),
    );

    _isActive = widget.initialIsActive;
  }

  // =============================================================
  // DISPOSE
  // =============================================================

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _gradeController.dispose();
    _displayOrderController.dispose();
    _baseSalaryController.dispose();

    super.dispose();
  }

  // =============================================================
  // SAVE
  // =============================================================

  Future<void> _save() async {
    if (widget.isLoading) {
      return;
    }

    FocusScope.of(context).unfocus();

    final form = _formKey.currentState;

    if (form == null) {
      return;
    }

    if (!form.validate()) {
      return;
    }

    final name = _nameController.text.trim();

    final description =
    _descriptionController.text.trim();

    final grade =
        int.tryParse(
          _gradeController.text.trim(),
        ) ??
            1;

    final displayOrder =
        int.tryParse(
          _displayOrderController.text.trim(),
        ) ??
            0;

    final baseSalary =
        double.tryParse(
          _baseSalaryController.text.trim(),
        ) ??
            0;

    await widget.onSubmit(
      name,
      description,
      grade,
      displayOrder,
      baseSalary,
      _isActive,
    );
  }

  // =============================================================
  // BUILD
  // =============================================================

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    final width = MediaQuery.sizeOf(context).width;

    final bool isDesktop = width >= 900;
    final bool isTablet =
        width >= 600 && width < 900;

    final double sectionSpacing = isDesktop
        ? 20
        : isTablet
        ? 18
        : 16;

    final double cardPadding = isDesktop
        ? 16
        : isTablet
        ? 14
        : 12;

    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment:
        CrossAxisAlignment.stretch,
        children: [
          // =====================================================
          // BASIC INFORMATION SECTION
          // =====================================================

          _buildSectionHeader(
            context,
            icon: Icons.badge_outlined,
            title: 'Designation Information',
            subtitle:
            'Enter the basic designation details.',
          ),

          SizedBox(height: sectionSpacing),

          // =====================================================
          // DESIGNATION NAME
          // =====================================================

          AppTextField(
            controller: _nameController,
            label: 'Designation Name',
            prefixIcon: Icons.badge_outlined,
            validator: (value) {
              if (value == null ||
                  value.trim().isEmpty) {
                return 'Designation name is required';
              }

              return null;
            },
          ),

          const SizedBox(height: 16),

          // =====================================================
          // DESCRIPTION
          // =====================================================

          AppTextField(
            controller: _descriptionController,
            label: 'Description',
            prefixIcon:
            Icons.description_outlined,
            maxLines: 3,
          ),

          SizedBox(height: sectionSpacing),

          // =====================================================
          // EMPLOYMENT SETTINGS SECTION
          // =====================================================

          _buildSectionHeader(
            context,
            icon: Icons.tune_outlined,
            title: 'Designation Settings',
            subtitle:
            'Configure grade, order and salary.',
          ),

          SizedBox(height: sectionSpacing),

          // =====================================================
          // GRADE / DISPLAY ORDER / SALARY
          //
          // Desktop:
          // 3 columns
          //
          // Tablet:
          // 3 columns
          //
          // Mobile:
          // vertical
          // =====================================================

          if (isDesktop || isTablet)
            Row(
              crossAxisAlignment:
              CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: _buildGradeField(),
                ),

                const SizedBox(width: 12),

                Expanded(
                  child: _buildDisplayOrderField(),
                ),

                const SizedBox(width: 12),

                Expanded(
                  child: _buildSalaryField(),
                ),
              ],
            )
          else ...[
            _buildGradeField(),

            const SizedBox(height: 16),

            _buildDisplayOrderField(),

            const SizedBox(height: 16),

            _buildSalaryField(),
          ],

          SizedBox(height: sectionSpacing),

          // =====================================================
          // STATUS SECTION
          // =====================================================

          _buildSectionHeader(
            context,
            icon: Icons.toggle_on_outlined,
            title: 'Status',
            subtitle:
            'Control whether this designation is active.',
          ),

          const SizedBox(height: 12),

          Container(
            width: double.infinity,
            padding: EdgeInsets.all(cardPadding),
            decoration: BoxDecoration(
              color: colorScheme.surfaceContainerLow,
              borderRadius:
              BorderRadius.circular(16),
              border: Border.all(
                color: colorScheme.outlineVariant,
              ),
            ),
            child: AppCheckbox(
              title: 'Active Designation',
              value: _isActive,
              onChanged: widget.isLoading
                  ? (_) {}
                  : (value) {
                if (!mounted) {
                  return;
                }

                setState(() {
                  _isActive =
                      value ?? true;
                });
              },
            ),
          ),

          const SizedBox(height: 28),

          // =====================================================
          // SAVE / UPDATE BUTTON
          // =====================================================

          AppButton(
            text: widget.initialName
                .trim()
                .isEmpty
                ? 'Save Designation'
                : 'Update Designation',
            icon: widget.initialName
                .trim()
                .isEmpty
                ? Icons.save_outlined
                : Icons.check_circle_outline,
            isLoading: widget.isLoading,
            onPressed: _save,
          ),

          const SizedBox(height: 10),

          // =====================================================
          // HELPER TEXT
          // =====================================================

          Text(
            'Designation information will be securely saved.',
            textAlign: TextAlign.center,
            style: theme.textTheme.bodySmall?.copyWith(
              color: colorScheme.onSurfaceVariant,
            ),
          ),
        ],
      ),
    );
  }

  // =============================================================
  // GRADE FIELD
  // =============================================================

  Widget _buildGradeField() {
    return AppTextField(
      controller: _gradeController,
      label: 'Grade',
      prefixIcon: Icons.sort_rounded,
      keyboardType: TextInputType.number,
      validator: (value) {
        if (value == null ||
            value.trim().isEmpty) {
          return 'Grade is required';
        }

        final grade =
        int.tryParse(value.trim());

        if (grade == null) {
          return 'Invalid grade';
        }

        return null;
      },
    );
  }

  // =============================================================
  // DISPLAY ORDER FIELD
  // =============================================================

  Widget _buildDisplayOrderField() {
    return AppTextField(
      controller: _displayOrderController,
      label: 'Display Order',
      prefixIcon:
      Icons.format_list_numbered_rounded,
      keyboardType: TextInputType.number,
      validator: (value) {
        if (value == null ||
            value.trim().isEmpty) {
          return 'Display Order is required';
        }

        final order =
        int.tryParse(value.trim());

        if (order == null) {
          return 'Invalid number';
        }

        return null;
      },
    );
  }

  // =============================================================
  // BASE SALARY FIELD
  // =============================================================

  Widget _buildSalaryField() {
    return AppTextField(
      controller: _baseSalaryController,
      label: 'Base Salary',
      prefixIcon:
      Icons.payments_outlined,
      keyboardType:
      const TextInputType.numberWithOptions(
        decimal: true,
      ),
      validator: (value) {
        if (value == null ||
            value.trim().isEmpty) {
          return null;
        }

        final salary =
        double.tryParse(value.trim());

        if (salary == null) {
          return 'Invalid salary';
        }

        if (salary < 0) {
          return 'Salary cannot be negative';
        }

        return null;
      },
    );
  }

  // =============================================================
  // SECTION HEADER
  // =============================================================

  Widget _buildSectionHeader(
      BuildContext context, {
        required IconData icon,
        required String title,
        required String subtitle,
      }) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Row(
      crossAxisAlignment:
      CrossAxisAlignment.start,
      children: [
        Container(
          width: 40,
          height: 40,
          decoration: BoxDecoration(
            color: colorScheme.primaryContainer,
            borderRadius:
            BorderRadius.circular(12),
          ),
          alignment: Alignment.center,
          child: Icon(
            icon,
            size: 20,
            color:
            colorScheme.onPrimaryContainer,
          ),
        ),

        const SizedBox(width: 11),

        Expanded(
          child: Column(
            crossAxisAlignment:
            CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style:
                theme.textTheme.titleMedium
                    ?.copyWith(
                  fontWeight: FontWeight.w800,
                  letterSpacing: -0.1,
                ),
              ),

              const SizedBox(height: 2),

              Text(
                subtitle,
                style:
                theme.textTheme.bodySmall
                    ?.copyWith(
                  color:
                  colorScheme.onSurfaceVariant,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}