import '../../domain/entities/role_entity.dart';

class RoleModel extends RoleEntity {
  const RoleModel({
    required super.id,
    required super.companyId,
    required super.roleCode,
    required super.roleName,
    required super.description,
    required super.isActive,
    required super.createdAt,
    required super.updatedAt,
    super.createdBy,
    super.updatedBy,
  });

  factory RoleModel.fromJson(
      Map<String, dynamic> json,
      ) {
    return RoleModel(
      id: json['id'] ?? '',
      companyId: json['company_id'] ?? '',
      roleCode: json['role_code'] ?? '',
      roleName: json['role_name'] ?? '',
      description: json['description'] ?? '',
      isActive: json['is_active'] ?? true,
      createdAt: DateTime.parse(
        json['created_at'],
      ),
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.parse(
        json['updated_at'],
      ),
      createdBy: json['created_by'],
      updatedBy: json['updated_by'],
    );
  }


  /// For Create Operation
  /// id will be generated by Supabase/PostgreSQL
  Map<String, dynamic> toCreateJson() {
    return {
      'company_id': companyId,
      'role_code': roleCode,
      'role_name': roleName,
      'description': description,
      'is_active': isActive,
      'created_at': createdAt.toIso8601String(),

      if (updatedAt != null)
        'updated_at': updatedAt!.toIso8601String(),

      if (createdBy != null && createdBy!.isNotEmpty)
        'created_by': createdBy,
    };
  }


  /// For Update Operation
  /// id is required for update condition
  Map<String, dynamic> toUpdateJson() {
    return {
      'company_id': companyId,
      'role_code': roleCode,
      'role_name': roleName,
      'description': description,
      'is_active': isActive,

      if (updatedAt != null)
        'updated_at': updatedAt!.toIso8601String(),

      if (updatedBy != null && updatedBy!.isNotEmpty)
        'updated_by': updatedBy,
    };
  }


  /// Optional: Normal JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'company_id': companyId,
      'role_code': roleCode,
      'role_name': roleName,
      'description': description,
      'is_active': isActive,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
      'created_by': createdBy,
      'updated_by': updatedBy,
    };
  }
}